# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2815c83ac04adf4804aeca64b8e1511e90a85530b09846d8e90a4e3745309cdd309ba7200047a84da4605043601925cfd62e51dfa59ae62a117c21d27ac2c61

test:
  secret_key_base: 86683cd31a2cd60b6b05f58ed07eab5701c1f6d0087ad54e1ce52002514fa3e2fffcff40b433fa9e3012a92630920c8e9d279e3b53e1e9d491c85880c6d0c827

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
